'use strict';
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  // Window controls
  windowMinimize: ()      => ipcRenderer.send('window-minimize'),
  windowMaximize: ()      => ipcRenderer.send('window-maximize'),
  windowClose:    ()      => ipcRenderer.send('window-close'),

  // Settings
  getSettings:    ()      => ipcRenderer.invoke('settings-get'),
  saveSettings:   (s)     => ipcRenderer.invoke('settings-save', s),
  getSkaldTheme:  ()      => ipcRenderer.invoke('skald-theme-get'),
  setSkaldTheme:  (theme) => ipcRenderer.invoke('skald-theme-set', theme),
  chooseFolder:   ()      => ipcRenderer.invoke('choose-folder'),
  scanMusicLibrary: (opts)=> ipcRenderer.invoke('music-library-scan', opts),
  listFolders:    (opts)  => ipcRenderer.invoke('folder-browser-list', opts),
  createFolder:   (opts)  => ipcRenderer.invoke('folder-browser-create', opts),
  listProfileGamerPics: () => ipcRenderer.invoke('profile-gamerpics-list'),
  rerunArtMigration: ()   => ipcRenderer.invoke('storage-rerun-art-migration'),
  clearCatalogCache: ()   => ipcRenderer.invoke('storage-clear-catalog-cache'),
  clearArtCache:    ()    => ipcRenderer.invoke('storage-clear-art-cache'),
  openStoragePath:  (opts)=> ipcRenderer.invoke('storage-open-path', opts),

  // Library
  getLibrary:     ()      => ipcRenderer.invoke('library-get'),
  getLibraryGame: (opts)  => ipcRenderer.invoke('library-get-game',    opts),
  upsertLibraryMetadata: (opts) => ipcRenderer.invoke('library-upsert-metadata', opts),
  enrichLibraryGame: (opts) => ipcRenderer.invoke('library-enrich-game', opts),
  previewGameMetadata: (opts) => ipcRenderer.invoke('metadata-preview-game', opts),
  scrapeLaunchBoxForLibraryGame: (opts) => ipcRenderer.invoke('launchbox-scrape-library-game', opts),
  searchLaunchBoxForLibraryGame: (opts) => ipcRenderer.invoke('launchbox-search-library-game', opts),
  searchLaunchBoxForMarketplaceGame: (opts) => ipcRenderer.invoke('launchbox-search-marketplace-game', opts),
  scrapeLaunchBoxForMarketplaceGame: (opts) => ipcRenderer.invoke('launchbox-scrape-marketplace-game', opts),
  scrapeLaunchBoxSystemMetadata: (opts) => ipcRenderer.invoke('launchbox-scan-library-system', opts),
  scrapeLaunchBoxMarketplaceSystems: (opts) => ipcRenderer.invoke('launchbox-scan-marketplace-systems', opts),
  onLaunchBoxScrapeProgress: (cb) => ipcRenderer.on('launchbox-scrape-progress', (_, data) => cb(data)),
  exportSystemMetadataPack: (opts) => ipcRenderer.invoke('metadata-export-system-pack', opts),
  getPackagedMarketplaceMetadata: (opts) => ipcRenderer.invoke('marketplace-packaged-metadata', opts),
  getPackagedMarketplaceMetadataStats: (opts) => ipcRenderer.invoke('marketplace-packaged-metadata-stats', opts),
  getRpcnStatusBatch: (opts) => ipcRenderer.invoke('rpcn-status-batch', opts),
  getRpcnBrowserStats: (opts) => ipcRenderer.invoke('rpcn-browser-stats', opts),
  getInsigniaStatusBatch: (opts) => ipcRenderer.invoke('insignia-status-batch', opts),
  markLibraryPlayed: (opts) => ipcRenderer.invoke('library-mark-played', opts),
  checkMetadataService: () => ipcRenderer.invoke('metadata-service-health'),
  setCategory:    (opts)  => ipcRenderer.invoke('library-set-category', opts),
  setFavorite:    (opts)  => ipcRenderer.invoke('library-set-favorite', opts),
  setNotes:       (opts)  => ipcRenderer.invoke('library-set-notes',    opts),

  // Collections
  getCollections:       ()     => ipcRenderer.invoke('collections-get'),
  createCollection:     (opts) => ipcRenderer.invoke('collections-create',     opts),
  deleteCollection:     (opts) => ipcRenderer.invoke('collections-delete',     opts),
  renameCollection:     (opts) => ipcRenderer.invoke('collections-rename',     opts),
  addGameToCollection:  (opts) => ipcRenderer.invoke('collections-add-game',   opts),
  removeGameFromCollection: (opts) => ipcRenderer.invoke('collections-remove-game', opts),
  setCollectionColor:   (opts) => ipcRenderer.invoke('collections-set-color',  opts),

  // Download
  fetchFileList:  (opts)  => ipcRenderer.invoke('fetch-file-list', opts),
  downloadStart:  (opts)  => ipcRenderer.invoke('download-start',  opts),
  downloadCancel: (opts)  => ipcRenderer.invoke('download-cancel', opts),
  marketplaceInstall: (opts) => ipcRenderer.invoke('marketplace-install', opts),
  archiveProbeDownload: (opts) => ipcRenderer.invoke('archiveorg-probe-download', opts),
  fetchMarketplaceThemesCatalog: (opts) => ipcRenderer.invoke('marketplace-themes-catalog', opts),
  inspectMarketplaceThemeFolder: (opts) => ipcRenderer.invoke('marketplace-theme-folder-inspect', opts),
  downloadMarketplaceThemeFolder: (opts) => ipcRenderer.invoke('marketplace-theme-folder-download', opts),
  listDownloadedMarketplaceThemes: () => ipcRenderer.invoke('marketplace-themes-downloaded'),
  deleteMarketplaceTheme: (opts) => ipcRenderer.invoke('marketplace-theme-delete', opts),
  fetchMarketplacePs3AvatarCatalog: (opts) => ipcRenderer.invoke('marketplace-gamerpics-ps3-catalog', opts),
  listMarketplacePs3AvatarArchivePack: (opts) => ipcRenderer.invoke('marketplace-gamerpics-ps3-archive-pack', opts),
  downloadMarketplacePs3AvatarImage: (opts) => ipcRenderer.invoke('marketplace-gamerpics-ps3-archive-download', opts),
  fetchMarketplaceXbox360GamerpicCatalog: (opts) => ipcRenderer.invoke('marketplace-gamerpics-xbox360-catalog', opts),
  listMarketplaceXbox360GamerpicPack: (opts) => ipcRenderer.invoke('marketplace-gamerpics-xbox360-pack', opts),
  downloadMarketplaceXbox360Gamerpic: (opts) => ipcRenderer.invoke('marketplace-gamerpics-xbox360-download', opts),
  onDownloadProgress: (cb) => ipcRenderer.on('download-progress', (_, data) => cb(data)),

  // Extract / Install / Delete
  extractArchive: (opts)  => ipcRenderer.invoke('extract-archive', opts),
  installGame:    (opts)  => ipcRenderer.invoke('install-game',    opts),
  setExePath:     (opts)  => ipcRenderer.invoke('set-exe-path',    opts),
  deleteGame:     (opts)  => ipcRenderer.invoke('delete-game',     opts),
  findExes:       (opts)  => ipcRenderer.invoke('find-exes',       opts),

  // Launch
  launchGame:     (opts)  => ipcRenderer.invoke('launch-game',         opts),
  openGameLocation: (opts)=> ipcRenderer.invoke('open-game-location',  opts),
  readReadme:     (opts)  => ipcRenderer.invoke('read-readme',         opts),

  // ROM list + launch
  fetchRomList:       (opts)  => ipcRenderer.invoke('fetch-rom-list', opts),
  listMarketplaceSources: (opts) => ipcRenderer.invoke('marketplace-list-sources', opts),
  fetchMarketplaceCatalog: (opts) => ipcRenderer.invoke('marketplace-fetch-catalog', opts),
  onRomFetchProgress: (cb)   => ipcRenderer.on('rom-fetch-progress', (_, d) => cb(d)),
  clearRomCache:  (opts)  => ipcRenderer.invoke('clear-rom-cache',  opts), // opts: { system }
  launchRom:      (opts)  => ipcRenderer.invoke('launch-rom',     opts),
  getEmulatorSessions: () => ipcRenderer.invoke('emulator-sessions-get'),
  launchStandaloneEmulator: (opts) => ipcRenderer.invoke('emulator-launch-standalone', opts),
  focusSkaldShell: () => ipcRenderer.invoke('skald-shell-focus'),
  getEmulatorRuntimeStatus: () => ipcRenderer.invoke('emulator-runtime-status'),
  getPCSX2RuntimeStatus: () => ipcRenderer.invoke('pcsx2-runtime-status'),
  getPCSX2DisplaySettings: () => ipcRenderer.invoke('pcsx2-display-settings-get'),
  setPCSX2DisplaySettings: (opts) => ipcRenderer.invoke('pcsx2-display-settings-set', opts),
  getPCSX2AudioSettings: () => ipcRenderer.invoke('pcsx2-audio-settings-get'),
  setPCSX2AudioSettings: (opts) => ipcRenderer.invoke('pcsx2-audio-settings-set', opts),
  getPCSX2SpeedSettings: () => ipcRenderer.invoke('pcsx2-speed-settings-get'),
  setPCSX2SpeedSettings: (opts) => ipcRenderer.invoke('pcsx2-speed-settings-set', opts),
  getDuckStationRuntimeStatus: () => ipcRenderer.invoke('duckstation-runtime-status'),
  getDuckStationGuideSettings: () => ipcRenderer.invoke('duckstation-guide-settings-get'),
  setDuckStationGuideSettings: (opts) => ipcRenderer.invoke('duckstation-guide-settings-set', opts),
  getDuckStationDisplaySettings: () => ipcRenderer.invoke('duckstation-display-settings-get'),
  setDuckStationDisplaySettings: (opts) => ipcRenderer.invoke('duckstation-display-settings-set', opts),
  getDuckStationAudioSettings: () => ipcRenderer.invoke('duckstation-audio-settings-get'),
  setDuckStationAudioSettings: (opts) => ipcRenderer.invoke('duckstation-audio-settings-set', opts),
  getDuckStationSpeedSettings: () => ipcRenderer.invoke('duckstation-speed-settings-get'),
  setDuckStationSpeedSettings: (opts) => ipcRenderer.invoke('duckstation-speed-settings-set', opts),
  openDuckStationTexturesDirectory: () => ipcRenderer.invoke('duckstation-textures-dir-open'),
  getDuckStationUpdateStatus: (opts) => ipcRenderer.invoke('duckstation-update-status', opts),
  skipDuckStationUpdateVersion: (opts) => ipcRenderer.invoke('duckstation-update-skip-version', opts),
  getDolphinRuntimeStatus: () => ipcRenderer.invoke('dolphin-runtime-status'),
  getCemuRuntimeStatus: () => ipcRenderer.invoke('cemu-runtime-status'),
  getXemuRuntimeStatus: () => ipcRenderer.invoke('xemu-runtime-status'),
  getCemuControllerConfig: () => ipcRenderer.invoke('cemu-controller-config-get'),
  applyCemuControllerPreset: (opts) => ipcRenderer.invoke('cemu-controller-preset-apply', opts),
  getRPCS3RuntimeStatus: () => ipcRenderer.invoke('rpcs3-runtime-status'),
  getRPCS3SetupStatus: () => ipcRenderer.invoke('rpcs3-setup-status'),
  getRPCS3Config: () => ipcRenderer.invoke('rpcs3-config-get'),
  setRPCS3Config: (opts) => ipcRenderer.invoke('rpcs3-config-set', opts),
  getRPCS3ControllerConfig: () => ipcRenderer.invoke('rpcs3-controller-config-get'),
  applyRPCS3ControllerPreset: (opts) => ipcRenderer.invoke('rpcs3-controller-preset-apply', opts),
  updateRPCS3SetupStatus: (opts) => ipcRenderer.invoke('rpcs3-setup-update', opts),
  runRPCS3WelcomeGuideAction: (opts) => ipcRenderer.invoke('rpcs3-welcome-guide-action', opts),
  getVLCRuntimeStatus: () => ipcRenderer.invoke('vlc-runtime-status'),
  getXeniaRuntimeStatus: () => ipcRenderer.invoke('xenia-runtime-status'),
  getXeniaProfileStatus: () => ipcRenderer.invoke('xenia-profile-status'),
  syncXeniaProfile: () => ipcRenderer.invoke('xenia-profile-sync'),
  getXeniaGuideSettings: () => ipcRenderer.invoke('xenia-guide-settings-get'),
  setXeniaGuideSettings: (opts) => ipcRenderer.invoke('xenia-guide-settings-set', opts),
  exportXeniaProfile: (opts) => ipcRenderer.invoke('xenia-profile-export', opts),
  importXeniaProfile: (opts) => ipcRenderer.invoke('xenia-profile-import', opts),
  openXeniaProfilePath: (opts) => ipcRenderer.invoke('xenia-profile-open-path', opts),
  getXeniaContentSummary: () => ipcRenderer.invoke('xenia-content-summary-get'),
  importXeniaContent: (opts) => ipcRenderer.invoke('xenia-content-import', opts),
  openXeniaContentTitle: (opts) => ipcRenderer.invoke('xenia-content-title-open', opts),
  removeXeniaContentTitle: (opts) => ipcRenderer.invoke('xenia-content-title-remove', opts),
  getXeniaGameProfileStatus: (opts) => ipcRenderer.invoke('xenia-game-profile-status', opts),
  setXeniaGameProfile: (opts) => ipcRenderer.invoke('xenia-game-profile-set', opts),
  getXeniaPatchStatus: (opts) => ipcRenderer.invoke('xenia-patch-status-get', opts),
  importXeniaPatch: (opts) => ipcRenderer.invoke('xenia-patch-import', opts),
  openXeniaPatchRoot: () => ipcRenderer.invoke('xenia-patch-open-root'),
  setXeniaMatchingPatches: (opts) => ipcRenderer.invoke('xenia-patch-set-matching', opts),
  syncPCSX2Runtime: () => ipcRenderer.invoke('pcsx2-runtime-sync'),
  syncDuckStationRuntime: () => ipcRenderer.invoke('duckstation-runtime-sync'),
  syncDolphinRuntime: () => ipcRenderer.invoke('dolphin-runtime-sync'),
  syncCemuRuntime: () => ipcRenderer.invoke('cemu-runtime-sync'),
  syncXemuRuntime: () => ipcRenderer.invoke('xemu-runtime-sync'),
  getLibretroCoreStatus: () => ipcRenderer.invoke('libretro-core-status'),
  downloadEmulatorRuntime: () => ipcRenderer.invoke('emulator-runtime-download'),
  uninstallEmulatorRuntime: () => ipcRenderer.invoke('emulator-runtime-uninstall'),
  downloadPCSX2Runtime: () => ipcRenderer.invoke('pcsx2-runtime-download'),
  uninstallPCSX2Runtime: () => ipcRenderer.invoke('pcsx2-runtime-uninstall'),
  downloadDuckStationRuntime: () => ipcRenderer.invoke('duckstation-runtime-download'),
  uninstallDuckStationRuntime: () => ipcRenderer.invoke('duckstation-runtime-uninstall'),
  downloadDolphinRuntime: (opts) => ipcRenderer.invoke('dolphin-runtime-download', opts),
  uninstallDolphinRuntime: (opts) => ipcRenderer.invoke('dolphin-runtime-uninstall', opts),
  downloadCemuRuntime: () => ipcRenderer.invoke('cemu-runtime-download'),
  uninstallCemuRuntime: () => ipcRenderer.invoke('cemu-runtime-uninstall'),
  downloadXemuRuntime: () => ipcRenderer.invoke('xemu-runtime-download'),
  uninstallXemuRuntime: () => ipcRenderer.invoke('xemu-runtime-uninstall'),
  downloadRPCS3Runtime: () => ipcRenderer.invoke('rpcs3-runtime-download'),
  uninstallRPCS3Runtime: () => ipcRenderer.invoke('rpcs3-runtime-uninstall'),
  downloadRPCS3Firmware: () => ipcRenderer.invoke('rpcs3-firmware-download'),
  installRPCS3Firmware: () => ipcRenderer.invoke('rpcs3-firmware-install'),
  downloadVLCRuntime: () => ipcRenderer.invoke('vlc-runtime-download'),
  uninstallVLCRuntime: () => ipcRenderer.invoke('vlc-runtime-uninstall'),
  downloadXeniaRuntime: () => ipcRenderer.invoke('xenia-runtime-download'),
  uninstallXeniaRuntime: () => ipcRenderer.invoke('xenia-runtime-uninstall'),
  downloadEmulatorCore: (opts) => ipcRenderer.invoke('emulator-core-download', opts),
  importEmulatorRuntime: (opts) => ipcRenderer.invoke('emulator-runtime-import', opts),
  importPCSX2Runtime: (opts) => ipcRenderer.invoke('pcsx2-runtime-import', opts),
  importDuckStationRuntime: (opts) => ipcRenderer.invoke('duckstation-runtime-import', opts),
  importDolphinRuntime: (opts) => ipcRenderer.invoke('dolphin-runtime-import', opts),
  importCemuRuntime: (opts) => ipcRenderer.invoke('cemu-runtime-import', opts),
  importXemuRuntime: (opts) => ipcRenderer.invoke('xemu-runtime-import', opts),
  importRPCS3Runtime: (opts) => ipcRenderer.invoke('rpcs3-runtime-import', opts),
  importVLCRuntime: (opts) => ipcRenderer.invoke('vlc-runtime-import', opts),
  importXeniaRuntime: (opts) => ipcRenderer.invoke('xenia-runtime-import', opts),
  getXeniaContentTrace: () => ipcRenderer.invoke('xenia-content-trace-get'),
  getEmulatorRuntimeProgress: () => ipcRenderer.invoke('emulator-runtime-progress-get'),
  onEmulatorRuntimeProgress: (cb) => ipcRenderer.on('emulator-runtime-progress', (_, data) => cb(data)),
  focusEmulatorSession: (opts) => ipcRenderer.invoke('emulator-session-focus', opts),
  closeEmulatorSession: (opts) => ipcRenderer.invoke('emulator-session-close', opts),
  restartEmulatorSession: (opts) => ipcRenderer.invoke('emulator-session-restart', opts),
  onEmulatorSessionsChanged: (cb) => ipcRenderer.on('emulator-sessions-changed', (_, sessions) => cb(sessions)),
  hltbSearch:     (opts)  => ipcRenderer.invoke('hltb-search',      opts),
  listHltbCache:    ()      => ipcRenderer.invoke('hltb-list-cache'),
  hltbPrefetchNext: (opts)  => ipcRenderer.invoke('hltb-prefetch-next', opts),
  getLibretroSystems: ()    => ipcRenderer.invoke('libretro-systems'),
  raGameSearch:   (opts)  => ipcRenderer.invoke('ra-game-search',   opts),
  raUserSummary:  ()      => ipcRenderer.invoke('ra-user-summary'),
  raRecentUnlocks:(opts)  => ipcRenderer.invoke('ra-recent-unlocks', opts),
  getRPCS3TrophiesForGame: (opts) => ipcRenderer.invoke('rpcs3-trophies-for-game', opts),
  getYouTubePlaylistDetails: (opts) => ipcRenderer.invoke('youtube-playlist-details', opts),
  getArchiveVideoDetails: (opts) => ipcRenderer.invoke('archive-video-details', opts),
  launchVLCMedia: (opts) => ipcRenderer.invoke('vlc-media-launch', opts),
  updateVLCMediaBounds: (opts) => ipcRenderer.invoke('vlc-media-bounds', opts),
  controlVLCMedia: (opts) => ipcRenderer.invoke('vlc-media-control', opts),
  onVLCMediaAction: (cb) => ipcRenderer.on('vlc-media-action', (_, data) => cb(data)),
  launchVLCAudio: (opts) => ipcRenderer.invoke('vlc-audio-launch', opts),
  controlVLCAudio: (opts) => ipcRenderer.invoke('vlc-audio-control', opts),
  openYouTubePlayer: (opts) => ipcRenderer.invoke('youtube-player-open', opts),
  closeYouTubePlayer: () => ipcRenderer.invoke('youtube-player-close'),

  // File picker (for RetroArch exe + core paths)
  chooseFile:     (opts)  => ipcRenderer.invoke('choose-file',   opts),

  // Archive.org login
  debugDumpHtml:          (opts) => ipcRenderer.invoke('debug-dump-html', opts),
  archiveAutoLogin:       ()     => ipcRenderer.invoke('archiveorg-autologin'),
  archiveSaveCredentials: (opts) => ipcRenderer.invoke('archiveorg-save-credentials', opts),
  archiveGetCredentials:  ()     => ipcRenderer.invoke('archiveorg-get-credentials'),
  archiveLogin:           (opts) => ipcRenderer.invoke('archiveorg-login',  opts),
  archiveLogout:          ()     => ipcRenderer.invoke('archiveorg-logout'),
  archiveCheck:           ()     => ipcRenderer.invoke('archiveorg-check'),

  // Auto-updater
  onUpdaterStatus: (cb) => ipcRenderer.on('updater-status', (_, data) => cb(data)),
  getUpdaterStatus: () => ipcRenderer.invoke('updater-status-get'),
  checkForUpdates: () => ipcRenderer.invoke('updater-check'),
  updaterInstall:  ()   => ipcRenderer.invoke('updater-install'),

  // Thumbnail cache
  getThumb:        (opts) => ipcRenderer.invoke('get-thumb', opts),

  // Scan for pre-existing installs
  scanForGames:    (opts) => ipcRenderer.invoke('scan-for-games', opts),

  // Add to Steam
  addToSteam:      (opts) => ipcRenderer.invoke('add-to-steam', opts),

  // App info
  getAppVersion:   () => ipcRenderer.invoke('app-version'),
  getHeroesPath:   () => ipcRenderer.invoke('heroes-path'),
  checkGameHero:   (opts) => ipcRenderer.invoke('check-game-hero', opts),
  getHomeAds:      (opts) => ipcRenderer.invoke('home-ads-list', opts),
  openExternal:    (url) => ipcRenderer.send('open-external', url),

  // Blades theme
  openBladesWindow:    ()      => ipcRenderer.invoke('blades-open'),
  openInitialSetup:    ()      => ipcRenderer.invoke('initial-setup-open'),
  completeInitialSetup:(opts)  => ipcRenderer.invoke('initial-setup-complete', opts),
  closeBladesWindow:   ()      => ipcRenderer.invoke('blades-close'),
  setBladesGuideOverlayState: (opts) => ipcRenderer.invoke('blades-guide-overlay-state', opts),
  openGuideOverlay:    ()      => ipcRenderer.invoke('guide-overlay-open'),
  closeGuideOverlay:   ()      => ipcRenderer.invoke('guide-overlay-close'),
  sendGuideOverlayCommand: (opts) => ipcRenderer.invoke('guide-overlay-command', opts),
  onGuideOverlayStateChanged: (cb) => ipcRenderer.on('guide-overlay-state-changed', (_, data) => cb(data)),
  onGuideOverlayCommand: (cb) => ipcRenderer.on('guide-overlay-command', (_, data) => cb(data)),
  bladesSelectSystem:  (opts)  => ipcRenderer.invoke('blades-select-system', opts),
  onBladesSystemSelected: (cb) => ipcRenderer.on('blades-system-selected', (_, data) => cb(data)),
  openThirdPartyAccountWindow: (opts) => ipcRenderer.invoke('thirdparty-open-window', opts),
  closeThirdPartyAccountWindow: () => ipcRenderer.invoke('thirdparty-close-window'),
  getThirdPartyAccount: (opts) => ipcRenderer.invoke('thirdparty-get-account', opts),
  saveThirdPartyAccount: (opts) => ipcRenderer.invoke('thirdparty-save-account', opts),
  clearThirdPartyAccount: (opts) => ipcRenderer.invoke('thirdparty-clear-account', opts),
  getSaveManagerStatus: () => ipcRenderer.invoke('save-manager-status'),
  listProfileSaves: () => ipcRenderer.invoke('save-manager-list'),
  getSaveCloudStatus: () => ipcRenderer.invoke('save-cloud-status'),
  connectDropboxSaveCloud: (opts) => ipcRenderer.invoke('save-cloud-dropbox-connect', opts),
  validateDropboxSaveCloud: (opts) => ipcRenderer.invoke('save-cloud-validate-dropbox', opts),
  setSaveCloudProvider: (opts) => ipcRenderer.invoke('save-cloud-provider-set', opts),
  setSaveCloudAutoBackup: (opts) => ipcRenderer.invoke('save-cloud-autobackup-set', opts),
  backupSaveCloudNow: () => ipcRenderer.invoke('save-cloud-backup-now'),
  restoreSaveCloudNow: () => ipcRenderer.invoke('save-cloud-restore-now'),
  onSaveCloudAutoBackupComplete: (cb) => ipcRenderer.on('save-cloud-auto-backup-complete', (_, data) => cb(data)),

  // Stoat Chat
  stoatLogin:          (opts)  => ipcRenderer.invoke('stoat-login',          opts),
  stoatLogout:         ()      => ipcRenderer.invoke('stoat-logout'),
  stoatStatus:         ()      => ipcRenderer.invoke('stoat-status'),
  stoatListProfiles:   ()      => ipcRenderer.invoke('stoat-list-profiles'),
  stoatUpdateProfileSnapshot: (opts) => ipcRenderer.invoke('stoat-update-profile-snapshot', opts),
  stoatSwitchProfile:  (opts)  => ipcRenderer.invoke('stoat-switch-profile', opts),
  stoatServers:        ()      => ipcRenderer.invoke('stoat-servers'),
  stoatChannels:       (opts)  => ipcRenderer.invoke('stoat-channels',       opts),
  stoatDMChannels:     ()      => ipcRenderer.invoke('stoat-dm-channels'),
  stoatMessages:       (opts)  => ipcRenderer.invoke('stoat-messages',       opts),
  stoatSendMessage:    (opts)  => ipcRenderer.invoke('stoat-send-message',   opts),
  stoatOpenDM:         (opts)  => ipcRenderer.invoke('stoat-open-dm',        opts),
  stoatFriends:        ()      => ipcRenderer.invoke('stoat-friends'),
  stoatServerMembers:  (opts)  => ipcRenderer.invoke('stoat-server-members', opts),
  stoatSetPresence:    (opts)  => ipcRenderer.invoke('stoat-set-presence',   opts),
  stoatClearPresence:  ()      => ipcRenderer.invoke('stoat-clear-presence'),
  showNativeNotification: (opts) => ipcRenderer.invoke('native-notification-show', opts),
  onStoatReady:        (cb)    => ipcRenderer.on('stoat-ready',          (_, d) => cb(d)),
  onStoatMessage:      (cb)    => ipcRenderer.on('stoat-message',        (_, d) => cb(d)),
  onStoatMessageUpdate:(cb)    => ipcRenderer.on('stoat-message-update', (_, d) => cb(d)),
  onStoatMessageDelete:(cb)    => ipcRenderer.on('stoat-message-delete', (_, d) => cb(d)),
  onStoatTypingStart:  (cb)    => ipcRenderer.on('stoat-typing-start',   (_, d) => cb(d)),
  onStoatTypingStop:   (cb)    => ipcRenderer.on('stoat-typing-stop',    (_, d) => cb(d)),
});
